name: release-solution-to-prod-reusable

on:
  workflow_call:  # Trigger manually
  push:
    branches:
      - main           # Or your release branch

jobs:
  release:
    runs-on: windows-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Power Platform CLI
      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions@v1
        with:
          version: latest

      # 3. Authenticate to Power Platform (Dev)
      - name: Authenticate (Dev)
        uses: microsoft/powerplatform-actions/authenticate@v1
        with:
          environment-url: ${{ inputs.BUILD_ENVIRONMENT_URL }}
          app-id: ${{ inputs.CLIENT_ID }}
          client-secret: ${{ secrets.envSecret }}
          tenant-id: ${{ inputs.TENANT_ID }}

      # 4. Export Solution from Dev
      - name: Export Solution from Dev
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          solution-name: Test
          path: out/solutions
          managed: false   # set true if you want managed solution

      # 5. Commit exported solution back to repo
      - name: Commit solution to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add out/solutions
          git commit -m "Export solution from Dev"
          git push

      # 6. Authenticate to Power Platform (Test/Prod)
      - name: Authenticate (Test)
        uses: microsoft/powerplatform-actions/authenticate@v1
        with:
          environment-url: ${{ inputs.PRODUCTION_ENVIRONMENT_URL}}
          app-id: ${{ inputs.CLIENT_ID }}
          client-secret: ${{ secrets.envSecret }}
          tenant-id: ${{ inputs.TENANT_ID }}

      # 7. Import solution into Test/Prod
      - name: Import Solution into Test
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ inputs.PRODUCTION_ENVIRONMENT_URL }}
          path: out/solutions/${{ inputs.solution_name }}.zip
          overwrite-unmanaged-customizations: true
          publish-changes: true
